export const INCLUIR_ANALISTA    = 'INCLUIR_ANALISTA';
export const ALTERAR_ANALISTA    = 'ALTERAR_ANALISTA';
export const EXCLUIR_ANALISTA    = 'EXCLUIR_ANALISTA';
export const CARREGAR_ANALISTAS  = 'CARREGAR_ANALISTA';
export const SELECIONAR_ANALISTA = 'SELECIONAR_ANALISTA';